### ISSUE TITLE
Nicely exporting/knitting correlation output

### ISSUE THREAD

**Issue by ArminNP** [easystats/correlation#109] opened 2020-11-15 14:17 UTC
What is the best way to export the outputs? It is "tidy" in the console. How can I export it to a word document. I used the report() function from the report package but I get an error.

**Comment by DominiqueMakowski** [comment] 2020-11-16 01:24
We don't yet fully support easy, accessible and consistent formatting to other formats, for instance in Rmarkdown, but that something we aim at adding.

As a first step here, I have added (you can update from github) a `format()` method that can be used on correlation objects and that transforms the raw data.frames into a data.frame of the output you see when it gets printed in the console (essentially, I moved the stuff that the `print()` method was doing to the `format()` method to decouple formatting from printing). 

 Now it is possible to put it a Rmarkdown table:

``` r
library(correlation)
library(dplyr)

correlation(iris) %>% 
  summary() %>% 
  format() %>% 
  knitr::kable()
```

<table>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: left;">Petal.Width</th>
<th style="text-align: left;">Petal.Length</th>
<th style="text-align: left;">Sepal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: left;">0.82***</td>
<td style="text-align: left;">0.87***</td>
<td style="text-align: left;">-0.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: left;">-0.37***</td>
<td style="text-align: left;">-0.43***</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: left;">0.96***</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>

<sup>Created on 2020-11-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


- Note that this is a provisional fix and might change once we start implementing a more consistent API for that across easystats.

- Also, this only works for the correlation matrices obtained for `summary()`, because the long output's printing and formatting is made via `parameters`. @strengejacke maybe we should do that, i.e., decouple the content of the printing methods to a `format()` method, for other objects? What do you think?

**Comment by strengejacke** [comment] 2020-11-18 07:47
Just in case we decide to have a generic `to_table()` function (see https://github.com/easystats/insight/issues/248), we have now an easy way to render tables into markdown, that also look nice in Word or PDF:

``` r
library(correlation)
library(magrittr)

correlation(iris) %>% 
  to_table()
```

<table>
<caption>Correlation Matrix (pearson-method)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: center;">Parameter2</th>
<th style="text-align: center;">r</th>
<th style="text-align: center;">CI_low</th>
<th style="text-align: center;">CI_high</th>
<th style="text-align: center;">t</th>
<th style="text-align: center;">df</th>
<th style="text-align: center;">p</th>
<th style="text-align: center;">Method</th>
<th style="text-align: center;">n_Obs</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">Sepal.Width</td>
<td style="text-align: center;">-0.12</td>
<td style="text-align: center;">-0.27</td>
<td style="text-align: center;">0.044</td>
<td style="text-align: center;">-1.4</td>
<td style="text-align: center;">148</td>
<td style="text-align: center;">1.5e-01</td>
<td style="text-align: center;">Pearson</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">Petal.Length</td>
<td style="text-align: center;">0.87</td>
<td style="text-align: center;">0.83</td>
<td style="text-align: center;">0.906</td>
<td style="text-align: center;">21.6</td>
<td style="text-align: center;">148</td>
<td style="text-align: center;">5.2e-47</td>
<td style="text-align: center;">Pearson</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">Petal.Width</td>
<td style="text-align: center;">0.82</td>
<td style="text-align: center;">0.76</td>
<td style="text-align: center;">0.865</td>
<td style="text-align: center;">17.3</td>
<td style="text-align: center;">148</td>
<td style="text-align: center;">9.3e-37</td>
<td style="text-align: center;">Pearson</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">Petal.Length</td>
<td style="text-align: center;">-0.43</td>
<td style="text-align: center;">-0.55</td>
<td style="text-align: center;">-0.288</td>
<td style="text-align: center;">-5.8</td>
<td style="text-align: center;">148</td>
<td style="text-align: center;">1.4e-07</td>
<td style="text-align: center;">Pearson</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">Petal.Width</td>
<td style="text-align: center;">-0.37</td>
<td style="text-align: center;">-0.50</td>
<td style="text-align: center;">-0.219</td>
<td style="text-align: center;">-4.8</td>
<td style="text-align: center;">148</td>
<td style="text-align: center;">8.1e-06</td>
<td style="text-align: center;">Pearson</td>
<td style="text-align: center;">150</td>
</tr>
<tr class="even">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: center;">Petal.Width</td>
<td style="text-align: center;">0.96</td>
<td style="text-align: center;">0.95</td>
<td style="text-align: center;">0.973</td>
<td style="text-align: center;">43.4</td>
<td style="text-align: center;">148</td>
<td style="text-align: center;">2.8e-85</td>
<td style="text-align: center;">Pearson</td>
<td style="text-align: center;">150</td>
</tr>
</tbody>
</table>

``` r

correlation(iris) %>% 
  summary() %>% 
  to_table()
```

<table>
<caption>Correlation Matrix (pearson-method)</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter</th>
<th style="text-align: center;">Petal.Width</th>
<th style="text-align: center;">Petal.Length</th>
<th style="text-align: center;">Sepal.Width</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">0.82***</td>
<td style="text-align: center;">0.87***</td>
<td style="text-align: center;">-0.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">-0.37***</td>
<td style="text-align: center;">-0.43***</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: center;">0.96***</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by strengejacke** [comment] 2020-11-18 08:16
@DominiqueMakowski is it safe to assume that the method and n_Obs-columns always have the same values (so we can remove these from the output)? If so, I suggest following output:

``` r
library(correlation)
library(magrittr)

correlation(iris) %>% 
  to_table()
```

<table>
<caption>Correlation Matrix</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Parameter1</th>
<th style="text-align: center;">Parameter2</th>
<th style="text-align: center;">r</th>
<th style="text-align: center;">95% CI</th>
<th style="text-align: center;">t(148)</th>
<th style="text-align: center;">p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">Sepal.Width</td>
<td style="text-align: center;">-0.12</td>
<td style="text-align: center;">(-0.27, 0.04)</td>
<td style="text-align: center;">-1.44</td>
<td style="text-align: center;">0.152</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">Petal.Length</td>
<td style="text-align: center;">0.87</td>
<td style="text-align: center;">(0.83, 0.91)</td>
<td style="text-align: center;">21.65</td>
<td style="text-align: center;">&lt; .001***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sepal.Length</td>
<td style="text-align: center;">Petal.Width</td>
<td style="text-align: center;">0.82</td>
<td style="text-align: center;">(0.76, 0.86)</td>
<td style="text-align: center;">17.30</td>
<td style="text-align: center;">&lt; .001***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">Petal.Length</td>
<td style="text-align: center;">-0.43</td>
<td style="text-align: center;">(-0.55, -0.29)</td>
<td style="text-align: center;">-5.77</td>
<td style="text-align: center;">&lt; .001***</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sepal.Width</td>
<td style="text-align: center;">Petal.Width</td>
<td style="text-align: center;">-0.37</td>
<td style="text-align: center;">(-0.50, -0.22)</td>
<td style="text-align: center;">-4.79</td>
<td style="text-align: center;">&lt; .001***</td>
</tr>
<tr class="even">
<td style="text-align: left;">Petal.Length</td>
<td style="text-align: center;">Petal.Width</td>
<td style="text-align: center;">0.96</td>
<td style="text-align: center;">(0.95, 0.97)</td>
<td style="text-align: center;">43.39</td>
<td style="text-align: center;">&lt; .001***</td>
</tr>
</tbody>
</table>

Method: Pearson (150 observations)

<sup>Created on 2020-11-18 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by DominiqueMakowski** [comment] 2020-11-19 02:38
> @DominiqueMakowski is it safe to assume that the method and n_Obs-columns always have the same values

Not really, the problem is that because we use pairwise deletion by default, the n_Obs column can theoretically be different. That said, we could make a rule that if `length(unique(x)) == 1` then we skip it otherwise we display it?

**Comment by strengejacke** [comment] 2020-11-19 07:29
ok, fixed. Just let me know what you think about the `to_table()` idea. The generic would be in _insight_, and submission is planned by the end of November (so some packages can be updated before the xmas break of the CRAN team).

**Comment by strengejacke** [comment] 2020-11-23 10:44
I think we can close this, see discussion here: https://github.com/easystats/insight/issues/248

**Closed by strengejacke** 2020-11-23 10:44 UTC
